### ISSUE TITLE
Definir Roles

### ISSUE THREAD

**Issue by carlosazaustre** [OSWeekends/kienba#3]
Definir que va hacer cada integrante del equipo y en que puede ayudar.

- [x] **Líder**: Se encargará de revisar y aceptar los pull-request
- [x] **Product Owner**: Se encargará de definir que funcionalidades a nivel de producto debe tener la aplicación
- [x] **Contributors**: Resto del equipo que aportará con código, bugs, issues, ideas, etc...

**Comment by carlosazaustre** [comment]
Hola Equipo!
Como ha sugerido Theba tenemos los siguientes roles a tener en cuenta:

- **Lider de Proyecto/Scrum Master:** @MoniAguado
- **Product Owner:** @carlosazaustre
- **Contributors**: Resto del Equipo

En el mundo de Scrum (al menos lo poco que sé) El Product Owner no está en las reuniones semanales con el resto del equipo. Normalmente porque en organizaciones corporativas, el Product Owner es el cliente y el Scrum Master es la persona que trabaja como enlace. Creo que en nuestro caso sería una ayuda al Scrum Master y podemos trabajar de forma conjunta.

No me queda claro quien se encargaría de aceptar los Pull Request y llevar un control de la arquitectura de la aplicación. En caso de que nadie quiera, me propongo yo mismo en esa labor.

Por supuesto con el tiempo veremos que llevamos mejor cada un@ y podemos evolucionar y adaptarnos e ir cambiando roles. Lo importante es aprender y pasarlo bien :)

Se admite debate :)

**Comment by MoniAguado** [comment]
En Adalab, también concretábamos rol de team building y de aprendizaje, quizás puedan ser útiles ya que tenemos que aprender nuevas herramientas. Qué os parece? Por lo demás, todo lo que comentas me parece guay :)

**Comment by carlosazaustre** [comment]
Perfecto! :)
Si, yo creo que aquí tod@s nos apoyaremos en tod@s. Si alguien tiene una duda o problema que no tenga problema en preguntar y si alguien del equipo tiene conocimiento (ya sea poco o mucho) que aporte su visión y experiencia :)

Por la parte de Vue y Firebase, contad conmigo para lo que necesitéis y si no @baumannzone me echará una mano que también se está pegando con Vue ;)
