### ISSUE TITLE
Vue init

### ISSUE THREAD

**Issue by carlosazaustre** [OSWeekends/kienba#8]
General el scaffolding con Vue CLI (PWA Template)

**Comment by rubenGit** [comment]
https://github.com/vuejs-templates/pwa

**Comment by carlosazaustre** [comment]
Si, ésta template es la mejor. Se basa en la template `webpack` pero le añade todo el tema de Service Workers y demás para hacer una Progressive Web App :)

**Comment by baumannzone** [comment]
¿No experimentas con el `vue-cli v.3`?
